spring:
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/SpringBootDBTest
      username: springBootDBTestUser
      password: springBootDBTestPassword
      driver-class-name: com.mysql.cj.jdbc.Driver
